
interface property {
  use wasi:buffer-pool/data-types.{dimension};

  record fraction {
    numerator: u32,
    denominator: u32
  }

  enum property-key {
    /// The number of samples in a second. (fraction)
    /// Eg. frame rate for image sensors.
    sampling-rate,
    dimension,
  }

  variant property-value {
    fraction(fraction),
    dimension(dimension),
  }
}


